"""
HOW TO RUN THE FILE:
    python scripts/visualize_process_video.py

Prototype V2 - Final Process Visualization Video Generator

Purpose:
    Create the final visualization video for either:

    1. Normal recorded Prototype V2 experiments stored in:
       datasets/raw/videos

    2. Controlled validation experiments stored in:
       datasets/validation/videos

The script automatically locates the source video.

Inputs:
    datasets/analytics/raw_detections.csv
    datasets/analytics/detection_timeline.csv
    datasets/analytics/state_timeline.csv
    datasets/analytics/event_log.csv

Output:
    datasets/analytics/process_visualization.mp4

Important:
    This script does NOT perform YOLO inference again.

    It visualizes pipeline outputs already generated by:
        1. Offline inference
        2. Temporal filtering
        3. State machine
        4. Process analytics
"""


from pathlib import Path
import csv
from collections import defaultdict

import cv2


# ======================================================================
# PROJECT CONFIGURATION
# ======================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

ANALYTICS_FOLDER = PROJECT_ROOT / "datasets" / "analytics"

RAW_VIDEO_FOLDER = (
    PROJECT_ROOT
    / "datasets"
    / "raw"
    / "videos"
)

VALIDATION_VIDEO_FOLDER = (
    PROJECT_ROOT
    / "datasets"
    / "validation"
    / "videos"
)


RAW_DETECTIONS_FILE = (
    ANALYTICS_FOLDER
    / "raw_detections.csv"
)

DETECTION_TIMELINE_FILE = (
    ANALYTICS_FOLDER
    / "detection_timeline.csv"
)

STATE_TIMELINE_FILE = (
    ANALYTICS_FOLDER
    / "state_timeline.csv"
)

EVENT_LOG_FILE = (
    ANALYTICS_FOLDER
    / "event_log.csv"
)

OUTPUT_VIDEO_FILE = (
    ANALYTICS_FOLDER
    / "process_visualization.mp4"
)


# ======================================================================
# VISUALIZATION SETTINGS
# ======================================================================

FONT = cv2.FONT_HERSHEY_SIMPLEX

BOX_THICKNESS = 2

TEXT_THICKNESS = 2

SMALL_FONT_SCALE = 0.55

NORMAL_FONT_SCALE = 0.70

LARGE_FONT_SCALE = 0.90


# ======================================================================
# HELPER FUNCTIONS
# ======================================================================


def print_header(title):

    print()

    print("=" * 75)

    print(title)

    print("=" * 75)


def text_to_bool(value):

    return str(value).strip().lower() in {
        "true",
        "1",
        "yes",
    }


def safe_int(value, default=0):

    try:

        return int(float(value))

    except (ValueError, TypeError):

        return default


def safe_float(value, default=0.0):

    try:

        return float(value)

    except (ValueError, TypeError):

        return default


def find_column(
    fieldnames,
    candidates,
    description,
):

    for candidate in candidates:

        if candidate in fieldnames:

            return candidate

    raise ValueError(

        f"Could not find {description} column.\n"

        f"Tried:\n"
        f"{candidates}\n\n"

        f"Available columns:\n"
        f"{fieldnames}"
    )


def load_csv_rows(file_path):

    with open(
        file_path,
        "r",
        newline="",
        encoding="utf-8",
    ) as csv_file:

        reader = csv.DictReader(csv_file)

        rows = list(reader)

        fieldnames = reader.fieldnames or []

    return rows, fieldnames


def locate_source_video(source_video_name):

    """
    Locate the source video automatically.

    Search order:

        1. datasets/raw/videos
        2. datasets/validation/videos

    The raw-video folder is checked first so normal Prototype V2
    operation remains the default behaviour.
    """

    raw_video_path = (
        RAW_VIDEO_FOLDER
        / source_video_name
    )

    validation_video_path = (
        VALIDATION_VIDEO_FOLDER
        / source_video_name
    )


    if raw_video_path.exists():

        return (
            raw_video_path,
            "RAW DATASET VIDEO",
        )


    if validation_video_path.exists():

        return (
            validation_video_path,
            "VALIDATION VIDEO",
        )


    raise FileNotFoundError(

        "Source video could not be found.\n\n"

        f"Video name:\n"
        f"{source_video_name}\n\n"

        f"Checked raw video location:\n"
        f"{raw_video_path}\n\n"

        f"Checked validation video location:\n"
        f"{validation_video_path}"
    )


def draw_text_with_background(
    frame,
    text,
    position,
    font_scale,
    text_color,
    background_color,
    thickness=2,
    padding=5,
):

    x, y = position

    (text_width, text_height), baseline = (
        cv2.getTextSize(
            text,
            FONT,
            font_scale,
            thickness,
        )
    )


    top_left = (

        max(
            0,
            x - padding,
        ),

        max(
            0,
            y - text_height - padding,
        ),
    )


    bottom_right = (

        x + text_width + padding,

        y + baseline + padding,
    )


    cv2.rectangle(
        frame,
        top_left,
        bottom_right,
        background_color,
        -1,
    )


    cv2.putText(
        frame,
        text,
        (x, y),
        FONT,
        font_scale,
        text_color,
        thickness,
        cv2.LINE_AA,
    )


# ======================================================================
# MAIN PROCESS
# ======================================================================


def main():

    print_header(
        "PROTOTYPE V2 - FINAL PROCESS VISUALIZATION VIDEO"
    )


    print(f"Raw detections:\n{RAW_DETECTIONS_FILE}")

    print()

    print(
        f"Detection timeline:\n"
        f"{DETECTION_TIMELINE_FILE}"
    )

    print()

    print(f"State timeline:\n{STATE_TIMELINE_FILE}")

    print()

    print(f"Event log:\n{EVENT_LOG_FILE}")

    print()

    print(f"Output video:\n{OUTPUT_VIDEO_FILE}")


    # ==================================================================
    # VERIFY INPUT FILES
    # ==================================================================

    print_header(
        "VERIFYING INPUT FILES"
    )


    required_files = [

        RAW_DETECTIONS_FILE,

        DETECTION_TIMELINE_FILE,

        STATE_TIMELINE_FILE,

        EVENT_LOG_FILE,
    ]


    for file_path in required_files:

        if not file_path.exists():

            raise FileNotFoundError(

                f"Required file not found:\n"
                f"{file_path}"
            )

        print(
            f"Found: {file_path.name}"
        )


    # ==================================================================
    # LOAD DATA
    # ==================================================================

    print_header(
        "LOADING PIPELINE OUTPUTS"
    )


    (
        raw_detection_rows,
        raw_detection_fields,

    ) = load_csv_rows(

        RAW_DETECTIONS_FILE
    )


    (
        detection_timeline_rows,
        detection_timeline_fields,

    ) = load_csv_rows(

        DETECTION_TIMELINE_FILE
    )


    (
        state_rows,
        state_fields,

    ) = load_csv_rows(

        STATE_TIMELINE_FILE
    )


    (
        event_rows,
        event_fields,

    ) = load_csv_rows(

        EVENT_LOG_FILE
    )


    if not state_rows:

        raise ValueError(

            "State timeline contains no rows."
        )


    print(

        f"Raw detection rows       : "
        f"{len(raw_detection_rows)}"
    )


    print(

        f"Detection timeline rows  : "
        f"{len(detection_timeline_rows)}"
    )


    print(

        f"State timeline rows      : "
        f"{len(state_rows)}"
    )


    print(

        f"Event rows               : "
        f"{len(event_rows)}"
    )


    # ==================================================================
    # FIND REQUIRED COLUMNS
    # ==================================================================

    detection_frame_column = find_column(

        raw_detection_fields,

        [
            "frame_number",
            "source_frame_number",
            "frame_index",
        ],

        "raw detection frame number",
    )


    class_name_column = find_column(

        raw_detection_fields,

        [
            "class_name",
            "object_class",
            "class",
        ],

        "class name",
    )


    confidence_column = find_column(

        raw_detection_fields,

        [
            "confidence",
            "confidence_score",
            "conf",
        ],

        "confidence",
    )


    x1_column = find_column(

        raw_detection_fields,

        [
            "x1",
            "bbox_x1",
        ],

        "bounding-box x1",
    )


    y1_column = find_column(

        raw_detection_fields,

        [
            "y1",
            "bbox_y1",
        ],

        "bounding-box y1",
    )


    x2_column = find_column(

        raw_detection_fields,

        [
            "x2",
            "bbox_x2",
        ],

        "bounding-box x2",
    )


    y2_column = find_column(

        raw_detection_fields,

        [
            "y2",
            "bbox_y2",
        ],

        "bounding-box y2",
    )


    timeline_frame_column = find_column(

        detection_timeline_fields,

        [
            "frame_number",
            "source_frame_number",
            "frame_index",
        ],

        "detection timeline frame number",
    )


    state_frame_column = find_column(

        state_fields,

        [
            "frame_number",
            "source_frame_number",
            "frame_index",
        ],

        "state timeline frame number",
    )


    state_name_column = find_column(

        state_fields,

        [
            "assembly_state",
            "process_state",
            "state",
        ],

        "assembly state",
    )


    event_frame_column = find_column(

        event_fields,

        [
            "frame_number",
            "source_frame_number",
            "frame_index",
        ],

        "event frame number",
    )


    # ==================================================================
    # DETERMINE SOURCE VIDEO
    # ==================================================================

    print_header(
        "LOCATING SOURCE VIDEO"
    )


    if "source_video" not in state_fields:

        raise ValueError(

            "The state timeline does not contain "
            "a 'source_video' column.\n\n"

            f"Available columns:\n"
            f"{state_fields}"
        )


    source_videos = {

        str(
            row.get(
                "source_video",
                "",
            )
        ).strip()

        for row in state_rows

        if str(
            row.get(
                "source_video",
                "",
            )
        ).strip()
    }


    if len(source_videos) == 0:

        raise ValueError(

            "No source video name was found "
            "in state_timeline.csv."
        )


    if len(source_videos) != 1:

        raise ValueError(

            "Expected exactly one source video.\n\n"

            f"Source videos found:\n"
            f"{sorted(source_videos)}"
        )


    source_video_name = next(
        iter(source_videos)
    )


    (
        source_video_path,
        source_video_location,

    ) = locate_source_video(

        source_video_name
    )


    print(
        f"Video name        : "
        f"{source_video_name}"
    )


    print(
        f"Video source type : "
        f"{source_video_location}"
    )


    print(
        f"Source video path :\n"
        f"{source_video_path}"
    )


    # ==================================================================
    # INDEX RAW DETECTIONS BY FRAME
    # ==================================================================

    detections_by_frame = defaultdict(list)


    for row in raw_detection_rows:

        frame_number = safe_int(

            row[detection_frame_column]
        )


        detections_by_frame[
            frame_number
        ].append(row)


    # ==================================================================
    # INDEX DETECTION TIMELINE
    # ==================================================================

    detection_timeline_by_frame = {}


    for row in detection_timeline_rows:

        frame_number = safe_int(

            row[timeline_frame_column]
        )


        detection_timeline_by_frame[
            frame_number
        ] = row


    # ==================================================================
    # INDEX STATE TIMELINE
    # ==================================================================

    state_by_frame = {}


    for row in state_rows:

        frame_number = safe_int(

            row[state_frame_column]
        )


        state_by_frame[
            frame_number
        ] = row


    # ==================================================================
    # INDEX EVENTS BY FRAME
    # ==================================================================

    events_by_frame = defaultdict(list)


    for row in event_rows:

        frame_number = safe_int(

            row[event_frame_column]
        )


        events_by_frame[
            frame_number
        ].append(row)


    # ==================================================================
    # OPEN SOURCE VIDEO
    # ==================================================================

    print_header(
        "OPENING SOURCE VIDEO"
    )


    video_capture = cv2.VideoCapture(

        str(source_video_path)
    )


    if not video_capture.isOpened():

        raise RuntimeError(

            f"Could not open source video:\n"
            f"{source_video_path}"
        )


    fps = video_capture.get(

        cv2.CAP_PROP_FPS
    )


    width = int(

        video_capture.get(

            cv2.CAP_PROP_FRAME_WIDTH
        )
    )


    height = int(

        video_capture.get(

            cv2.CAP_PROP_FRAME_HEIGHT
        )
    )


    total_video_frames = int(

        video_capture.get(

            cv2.CAP_PROP_FRAME_COUNT
        )
    )


    if fps <= 0:

        video_capture.release()

        raise ValueError(

            f"Invalid source video FPS: {fps}"
        )


    if width <= 0 or height <= 0:

        video_capture.release()

        raise ValueError(

            "Invalid source video resolution.\n\n"

            f"Width  : {width}\n"

            f"Height : {height}"
        )


    print(f"FPS          : {fps:.3f}")

    print(f"Resolution   : {width} x {height}")

    print(f"Video frames : {total_video_frames}")


    # ==================================================================
    # PIPELINE / VIDEO CONSISTENCY CHECK
    # ==================================================================

    print_header(
        "PIPELINE / VIDEO CONSISTENCY CHECK"
    )


    state_timeline_frames = len(state_rows)

    detection_timeline_frames = len(
        detection_timeline_rows
    )


    print(

        f"Video frames              : "
        f"{total_video_frames}"
    )


    print(

        f"Detection timeline frames : "
        f"{detection_timeline_frames}"
    )


    print(

        f"State timeline frames     : "
        f"{state_timeline_frames}"
    )


    if (
        total_video_frames
        != state_timeline_frames
    ):

        print()

        print(
            "WARNING: Video frame count and "
            "state timeline row count differ."
        )


    if (
        total_video_frames
        != detection_timeline_frames
    ):

        print()

        print(
            "WARNING: Video frame count and "
            "detection timeline row count differ."
        )


    # ==================================================================
    # CREATE VIDEO WRITER
    # ==================================================================

    OUTPUT_VIDEO_FILE.parent.mkdir(

        parents=True,

        exist_ok=True,
    )


    if OUTPUT_VIDEO_FILE.exists():

        OUTPUT_VIDEO_FILE.unlink()


    fourcc = cv2.VideoWriter_fourcc(

        *"mp4v"
    )


    video_writer = cv2.VideoWriter(

        str(OUTPUT_VIDEO_FILE),

        fourcc,

        fps,

        (width, height),
    )


    if not video_writer.isOpened():

        video_capture.release()

        raise RuntimeError(

            f"Could not create output video:\n"
            f"{OUTPUT_VIDEO_FILE}"
        )


    # ==================================================================
    # VISUALIZATION PROCESS
    # ==================================================================

    print_header(
        "GENERATING VISUALIZATION VIDEO"
    )


    frame_number = 0

    processed_frames = 0


    transition_count = 0

    violation_count = 0

    completion_count = 0


    last_event_text = ""

    last_event_frame = -100000


    EVENT_DISPLAY_FRAMES = max(

        1,

        int(
            round(
                fps * 1.5
            )
        ),
    )


    while True:

        read_success, frame = (
            video_capture.read()
        )


        if not read_success:

            break


        # ==============================================================
        # DRAW YOLO DETECTIONS
        # ==============================================================

        frame_detections = (
            detections_by_frame.get(
                frame_number,
                [],
            )
        )


        for detection in frame_detections:

            class_name = detection[
                class_name_column
            ]


            confidence = safe_float(

                detection[
                    confidence_column
                ]
            )


            x1 = safe_int(
                detection[x1_column]
            )

            y1 = safe_int(
                detection[y1_column]
            )

            x2 = safe_int(
                detection[x2_column]
            )

            y2 = safe_int(
                detection[y2_column]
            )


            x1 = max(
                0,
                min(
                    x1,
                    width - 1,
                ),
            )

            y1 = max(
                0,
                min(
                    y1,
                    height - 1,
                ),
            )

            x2 = max(
                0,
                min(
                    x2,
                    width - 1,
                ),
            )

            y2 = max(
                0,
                min(
                    y2,
                    height - 1,
                ),
            )


            if class_name == "marker":

                box_color = (
                    0,
                    255,
                    0,
                )


            elif class_name == "power_adapter":

                box_color = (
                    255,
                    200,
                    0,
                )


            else:

                box_color = (
                    255,
                    255,
                    255,
                )


            cv2.rectangle(

                frame,

                (x1, y1),

                (x2, y2),

                box_color,

                BOX_THICKNESS,
            )


            label = (

                f"{class_name} "

                f"{confidence:.2f}"
            )


            label_y = max(

                25,

                y1 - 8,
            )


            draw_text_with_background(

                frame=frame,

                text=label,

                position=(
                    x1,
                    label_y,
                ),

                font_scale=SMALL_FONT_SCALE,

                text_color=(
                    0,
                    0,
                    0,
                ),

                background_color=box_color,

                thickness=1,
            )


        # ==============================================================
        # GET TEMPORALLY STABILIZED PRESENCE STATE
        # ==============================================================

        timeline_row = (
            detection_timeline_by_frame.get(
                frame_number
            )
        )


        if timeline_row is not None:

            stable_marker_present = text_to_bool(

                timeline_row.get(

                    "stable_marker_present",

                    False,
                )
            )


            stable_adapter_present = text_to_bool(

                timeline_row.get(

                    "stable_power_adapter_present",

                    False,
                )
            )


        else:

            stable_marker_present = False

            stable_adapter_present = False


        # ==============================================================
        # GET ASSEMBLY STATE
        # ==============================================================

        state_row = state_by_frame.get(

            frame_number
        )


        if state_row is not None:

            assembly_state = state_row[

                state_name_column
            ]


        else:

            assembly_state = (

                "NO_STATE_DATA"
            )


        # ==============================================================
        # PROCESS EVENTS
        # ==============================================================

        current_events = (

            events_by_frame.get(

                frame_number,

                [],
            )
        )


        for event in current_events:

            transition_count += 1


            if text_to_bool(

                event.get(

                    "sequence_violation",

                    False,
                )
            ):

                violation_count += 1


            if text_to_bool(

                event.get(

                    "assembly_completed",

                    False,
                )
            ):

                completion_count += 1


            last_event_text = event.get(

                "event_type",

                "UNKNOWN_EVENT",
            )


            last_event_frame = (

                frame_number
            )


        # ==============================================================
        # DRAW TOP INFORMATION PANEL
        # ==============================================================

        overlay = frame.copy()


        cv2.rectangle(

            overlay,

            (0, 0),

            (width, 145),

            (0, 0, 0),

            -1,
        )


        cv2.addWeighted(

            overlay,

            0.60,

            frame,

            0.40,

            0,

            frame,
        )


        timestamp_seconds = (

            frame_number / fps
        )


        cv2.putText(

            frame,

            "Prototype V2 Process Monitoring",

            (20, 30),

            FONT,

            NORMAL_FONT_SCALE,

            (255, 255, 255),

            TEXT_THICKNESS,

            cv2.LINE_AA,
        )


        cv2.putText(

            frame,

            (
                f"Frame: {frame_number}  "

                f"Time: "
                f"{timestamp_seconds:.2f} s"
            ),

            (20, 60),

            FONT,

            SMALL_FONT_SCALE,

            (255, 255, 255),

            1,

            cv2.LINE_AA,
        )


        cv2.putText(

            frame,

            (
                f"Stable presence | "

                f"Marker: "
                f"{'YES' if stable_marker_present else 'NO'}  "

                f"Adapter: "
                f"{'YES' if stable_adapter_present else 'NO'}"
            ),

            (20, 90),

            FONT,

            SMALL_FONT_SCALE,

            (255, 255, 255),

            1,

            cv2.LINE_AA,
        )


        cv2.putText(

            frame,

            f"Assembly state: "
            f"{assembly_state}",

            (20, 125),

            FONT,

            LARGE_FONT_SCALE,

            (255, 255, 255),

            TEXT_THICKNESS,

            cv2.LINE_AA,
        )


        # ==============================================================
        # DRAW RUNNING STATISTICS
        # ==============================================================

        statistics_text = (

            f"Transitions: "
            f"{transition_count} | "

            f"Violations: "
            f"{violation_count} | "

            f"Completions: "
            f"{completion_count}"
        )


        cv2.putText(

            frame,

            statistics_text,

            (20, height - 25),

            FONT,

            SMALL_FONT_SCALE,

            (255, 255, 255),

            1,

            cv2.LINE_AA,
        )


        # ==============================================================
        # DRAW RECENT EVENT
        # ==============================================================

        if (

            frame_number
            - last_event_frame

            <= EVENT_DISPLAY_FRAMES
        ):

            draw_text_with_background(

                frame=frame,

                text=(
                    f"EVENT: "
                    f"{last_event_text}"
                ),

                position=(

                    20,

                    height - 60,
                ),

                font_scale=(
                    NORMAL_FONT_SCALE
                ),

                text_color=(

                    255,
                    255,
                    255,
                ),

                background_color=(

                    60,
                    60,
                    60,
                ),

                thickness=2,
            )


        # ==============================================================
        # DRAW VIOLATION WARNING
        # ==============================================================

        current_violation = any(

            text_to_bool(

                event.get(

                    "sequence_violation",

                    False,
                )
            )

            for event in current_events
        )


        if current_violation:

            draw_text_with_background(

                frame=frame,

                text=(
                    "SEQUENCE VIOLATION"
                ),

                position=(

                    max(
                        20,
                        width - 320,
                    ),

                    height - 60,
                ),

                font_scale=(
                    NORMAL_FONT_SCALE
                ),

                text_color=(

                    255,
                    255,
                    255,
                ),

                background_color=(

                    0,
                    0,
                    255,
                ),

                thickness=2,
            )


        # ==============================================================
        # DRAW COMPLETION NOTIFICATION
        # ==============================================================

        current_completion = any(

            text_to_bool(

                event.get(

                    "assembly_completed",

                    False,
                )
            )

            for event in current_events
        )


        if current_completion:

            draw_text_with_background(

                frame=frame,

                text=(
                    "ASSEMBLY COMPLETION EVENT"
                ),

                position=(

                    max(
                        20,
                        width - 410,
                    ),

                    height - 100,
                ),

                font_scale=(
                    NORMAL_FONT_SCALE
                ),

                text_color=(

                    0,
                    0,
                    0,
                ),

                background_color=(

                    0,
                    255,
                    255,
                ),

                thickness=2,
            )


        # ==============================================================
        # WRITE OUTPUT FRAME
        # ==============================================================

        video_writer.write(frame)


        processed_frames += 1

        frame_number += 1


        if processed_frames % 100 == 0:

            print(

                f"Processed frames: "

                f"{processed_frames}/"

                f"{total_video_frames}"
            )


    # ==================================================================
    # RELEASE VIDEO RESOURCES
    # ==================================================================

    video_capture.release()

    video_writer.release()


    # ==================================================================
    # VERIFY OUTPUT VIDEO
    # ==================================================================

    print_header(
        "VERIFYING OUTPUT VIDEO"
    )


    if not OUTPUT_VIDEO_FILE.exists():

        raise FileNotFoundError(

            "Visualization processing finished, "
            "but the output video was not created."
        )


    output_file_size = (

        OUTPUT_VIDEO_FILE.stat().st_size
    )


    if output_file_size <= 0:

        raise RuntimeError(

            "Visualization output video exists "
            "but is empty."
        )


    print(
        "Output video created successfully."
    )


    print(

        f"Output file size : "
        f"{output_file_size / (1024 * 1024):.2f} MB"
    )


    # ==================================================================
    # FINAL CONSISTENCY CHECK
    # ==================================================================

    frame_count_match = (

        processed_frames
        == total_video_frames
    )


    state_count_match = (

        processed_frames
        == len(state_rows)
    )


    detection_timeline_count_match = (

        processed_frames
        == len(detection_timeline_rows)
    )


    print_header(
        "FINAL CONSISTENCY CHECK"
    )


    print(

        f"Processed / video frames match    : "
        f"{'YES' if frame_count_match else 'NO'}"
    )


    print(

        f"Processed / state rows match      : "
        f"{'YES' if state_count_match else 'NO'}"
    )


    print(

        f"Processed / detection rows match  : "
        f"{'YES' if detection_timeline_count_match else 'NO'}"
    )


    # ==================================================================
    # FINAL SUMMARY
    # ==================================================================

    print_header(
        "VISUALIZATION SUMMARY"
    )


    print(

        f"Source video              : "
        f"{source_video_name}"
    )


    print(

        f"Source video type         : "
        f"{source_video_location}"
    )


    print(

        f"Processed frames          : "
        f"{processed_frames}"
    )


    print(

        f"State transitions shown   : "
        f"{transition_count}"
    )


    print(

        f"Sequence violations shown : "
        f"{violation_count}"
    )


    print(

        f"Completion events shown   : "
        f"{completion_count}"
    )


    print()


    print(

        f"Output video saved to:\n"
        f"{OUTPUT_VIDEO_FILE}"
    )


    # ==================================================================
    # FINAL STATUS
    # ==================================================================

    print_header(
        "STATUS: FINAL PROCESS VISUALIZATION CREATED SUCCESSFULLY"
    )


    if not (
        frame_count_match
        and state_count_match
        and detection_timeline_count_match
    ):

        print(

            "WARNING: Visualization video was created, "
            "but one or more frame-count consistency "
            "checks did not match."
        )

        print()

        print(

            "Inspect the counts above before using "
            "this run as final validation evidence."
        )


    else:

        print(

            "Source video located successfully."
        )

        print(

            "Visualization video created successfully."
        )

        print(

            "Video and pipeline frame counts are consistent."
        )


    print()

    print(

        "Prototype V2 visualization stage completed."
    )


# ======================================================================
# SCRIPT ENTRY POINT
# ======================================================================


if __name__ == "__main__":

    main()